spring.application.name=backend-api
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=fabricio
spring.datasource.password=Fabricio44!
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
server.error.include-stacktrace=on_param
jwt.secret.key=c7b04530b1118f455f88fe5c6d3357f2edee635ebf27efcd71efe4cc5052d67e